104 story comments
CSC207-2022F-UofT/course-project-team-tree-dog pull request #119
Opened 2022-12-04 20:41 UTC by tostistos

2022-12-05 20:39 UTC, AlekseyPanas reviewed
Approved of core content, awaiting unit tests

2022-12-05 22:43 UTC, bac423 submitted a review, later dismissed
Awesome job

2022-12-06 20:46 UTC, AlekseyPanas approved these changes

2022-12-07 01:47 UTC, AlekseyPanas approved these changes

2022-12-07 02:09 UTC, joel-mat-03 commented on src/main/java/usecases/comment_as_guest/CagGatewayComments.java
> +     * @return true if adding the comment was successful
the method returns response and not boolean so you should describe the response

2022-12-07 02:16 UTC, joel-mat-03 requested changes

2022-12-07 02:16 UTC, joel-mat-03 commented on src/test/java/usecases/comment_as_guest/CagInteractorTests.java
> +         * @return "success" when commentAsGuestSuccess is true, and "failure" otherwise
i think this was originally implemented as method returning a string, so you would probably have to change it to 'return success or failure response' or something along those lines

2022-12-07 02:16 UTC, joel-mat-03 commented on src/main/java/usecases/get_story_comments/GscGatewayComments.java
> +     * @return a string array containing all the story comments, each one string
change this return description

2022-12-07 02:16 UTC, joel-mat-03 commented on src/test/java/usecases/get_story_comments/GscInteractorTests.java
> +         * and "failure" with null otherwise
once again, better to write 'success or failure response'. i am assuming this method was originally supposed to return a string

2022-12-07 02:29 UTC, joel-mat-03 approved these changes

2022-12-07 02:29 UTC, joel-mat-03 approved these changes

2022-12-07 03:24 UTC, bac423 approved these changes
Awesome job

2022-12-07 03:24 UTC, merged