21 use case run game
CSC207-2022F-UofT/course-project-team-tree-dog pull request #48
Opened 2022-11-13 00:05 UTC by bac423

Implemented without access to PGE use-case, but it should be fine

2022-11-15 18:09 UTC, AlekseyPanas requested changes
Interactor is perfect, just fix the tests

2022-11-15 22:17 UTC, AlekseyPanas approved these changes

2022-11-16 00:16 UTC, cotopaxi64 submitted a review, later dismissed
Looks good, and incredibly well documented!

2022-11-16 02:00 UTC, joel-mat-03 commented on src/test/java/usecases/run_game/RgTaskTests.java
> +        public void onTimerUpdate() {
write java docs for overriden methods except getters and setters

2022-11-16 02:20 UTC, joel-mat-03 requested changes
Documentation is good and all coding conventions are followed except for the one comment I have left regarding the java docs for the inner class CustomizableTestGame in RgTaskTests. Please make these changes.

2022-11-16 16:38 UTC, joel-mat-03 approved these changes
Looks good. Requested edits have been made and all conventions are followed.

2022-11-20 15:17 UTC, cotopaxi64 approved these changes
Looks good, and incredibly well documented!

2022-11-20 15:18 UTC, merged