59 use case get latest stories
CSC207-2022F-UofT/course-project-team-tree-dog pull request #75
Opened 2022-11-21 00:49 UTC by sarkar50-lab

2022-11-21 16:50 UTC, bac423 submitted a review, later dismissed
Alright

2022-11-21 16:54 UTC, cotopaxi64 submitted a review, later dismissed
Looks good to me.

2022-11-21 19:48 UTC, AlekseyPanas requested changes
Tests are perfectly documented and coverage is wonderful. The implementation of the use case is also mostly good but could use clarifying documentation in many areas. Please address my documentation remarks

2022-11-21 19:48 UTC, AlekseyPanas commented on src/main/java/usecases/get_latest_stories/GlsInputData.java
> +     * @param numToGet number of stories to get
Mention that this parameter can be provided as null to retrieve all stories

2022-11-21 19:48 UTC, AlekseyPanas commented on src/main/java/usecases/get_latest_stories/GlsOutputData.java
> +     * @return  data.numToGet StoryData retrieved from repo
also mention that they are sorted from latest date to earliest public date

2022-11-22 00:50 UTC, joel-mat-03 approved these changes
Code looks good and all conventions are followed

2022-11-22 01:05 UTC, bac423 approved these changes
[Quality Manager] Approved. Great job

2022-11-22 01:06 UTC, merged